### ISSUE TITLE
有关识别课程目录以及课程视频问题

### ISSUE THREAD

**Issue by B3eStCcc** [maxmeng93/auto-study#13]
今天测试中发现获取课程目录的时候，课程没有加载出来Chrome就直接闪退，不知道是自己网络问题还是网站更新后的问题,后来修改get课程代码得以解决 修改如下

await page.goto(url, {
    waitUntil: 'networkidle0' // 网络空闲说明加载完毕
  });

然后在获取课程学习内容进度的时候，在进行到某一科目的时候会报以下错误

Unhandled Rejection at: Promise Promise {
  <rejected> Error: Error: failed to find element matching selector ".activity-title > a.title"
      at ElementHandle.$eval (D:\Ouchn\auto-study-master\node_modules\puppeteer-core\lib\cjs\puppeteer\common\JSHandle.js:880:19)
      at runMicrotasks (<anonymous>)
      at processTicksAndRejections (node:internal/process/task_queues:96:5)
      at async getCourseDetail (D:\Ouchn\auto-study-master\src\getCourseDetail.js:35:19)
      at async getData (D:\Ouchn\auto-study-master\src\getData.js:13:24)
      at async D:\Ouchn\auto-study-master\src\index.js:59:3
} reason: Error: Error: failed to find element matching selector ".activity-title > a.title"
    at ElementHandle.$eval (D:\Ouchn\auto-study-master\node_modules\puppeteer-core\lib\cjs\puppeteer\common\JSHandle.js:880:19)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async getCourseDetail (D:\Ouchn\auto-study-master\src\getCourseDetail.js:35:19)
    at async getData (D:\Ouchn\auto-study-master\src\getData.js:13:24)
    at async D:\Ouchn\auto-study-master\src\index.js:59:3

请问需要如何解决？ 万分感谢！

**Comment by maxmeng93** [comment]
可能是网站改版或者你的科目和我的不一样，导致页面元素也不一样。

**Comment by 1xiaocainiao** [comment]
> 可能是网站改版或者你的科目和我的不一样，导致页面元素也不一样。

Unhandled Rejection at: Promise Promise {
  <rejected> ProtocolError: Protocol error (Runtime.callFunctionOn): Execution context was destroyed.
      at /Users/xxx/Downloads/auto-study-master/node_modules/puppeteer/lib/cjs/puppeteer/common/Connection.js:230:24
      at new Promise (<anonymous>)
      at CDPSession.send (/Users/xxx/Downloads/auto-study-master/node_modules/puppeteer/lib/cjs/puppeteer/common/Connection.js:226:16)
      at ExecutionContext._evaluateInternal (/Users/xxx/Downloads/auto-study-master/node_modules/puppeteer/lib/cjs/puppeteer/common/ExecutionContext.js:204:50)
      at ExecutionContext.evaluate (/Users/xxx/Downloads/auto-study-master/node_modules/puppeteer/lib/cjs/puppeteer/common/ExecutionContext.js:110:27)
      at DOMWorld.evaluate (/Users/xxx/Downloads/auto-study-master/node_modules/puppeteer/lib/cjs/puppeteer/common/DOMWorld.js:97:24)
      at runMicrotasks (<anonymous>)
      at processTicksAndRejections (node:internal/process/task_queues:96:5) {
    originalMessage: 'Execution context was destroyed.'
  }
} reason: ProtocolError: Protocol error (Runtime.callFunctionOn): Execution context was destroyed.
    at /Users/xxx/Downloads/auto-study-master/node_modules/puppeteer/lib/cjs/puppeteer/common/Connection.js:230:24
    at new Promise (<anonymous>)
    at CDPSession.send (/Users/xxx/Downloads/auto-study-master/node_modules/puppeteer/lib/cjs/puppeteer/common/Connection.js:226:16)
    at ExecutionContext._evaluateInternal (/Users/xxx/Downloads/auto-study-master/node_modules/puppeteer/lib/cjs/puppeteer/common/ExecutionContext.js:204:50)
    at ExecutionContext.evaluate (/Users/xxx/Downloads/auto-study-master/node_modules/puppeteer/lib/cjs/puppeteer/common/ExecutionContext.js:110:27)
    at DOMWorld.evaluate (/Users/xxx/Downloads/auto-study-master/node_modules/puppeteer/lib/cjs/puppeteer/common/DOMWorld.js:97:24)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  originalMessage: 'Execution context was destroyed.'
}

视频播放，测试了好几次，差不多一个小时，就会挂掉，是网站做了限制吗

**Comment by maxmeng93** [comment]
> > 可能是网站改版或者你的科目和我的不一样，导致页面元素也不一样。
> 
> Unhandled Rejection at: Promise Promise { ProtocolError: Protocol error (Runtime.callFunctionOn): Execution context was destroyed. at /Users/xxx/Downloads/auto-study-master/node_modules/puppeteer/lib/cjs/puppeteer/common/Connection.js:230:24 at new Promise () at CDPSession.send (/Users/xxx/Downloads/auto-study-master/node_modules/puppeteer/lib/cjs/puppeteer/common/Connection.js:226:16) at ExecutionContext._evaluateInternal (/Users/xxx/Downloads/auto-study-master/node_modules/puppeteer/lib/cjs/puppeteer/common/ExecutionContext.js:204:50) at ExecutionContext.evaluate (/Users/xxx/Downloads/auto-study-master/node_modules/puppeteer/lib/cjs/puppeteer/common/ExecutionContext.js:110:27) at DOMWorld.evaluate (/Users/xxx/Downloads/auto-study-master/node_modules/puppeteer/lib/cjs/puppeteer/common/DOMWorld.js:97:24) at runMicrotasks () at processTicksAndRejections (node:internal/process/task_queues:96:5) { originalMessage: 'Execution context was destroyed.' } } reason: ProtocolError: Protocol error (Runtime.callFunctionOn): Execution context was destroyed. at /Users/xxx/Downloads/auto-study-master/node_modules/puppeteer/lib/cjs/puppeteer/common/Connection.js:230:24 at new Promise () at CDPSession.send (/Users/xxx/Downloads/auto-study-master/node_modules/puppeteer/lib/cjs/puppeteer/common/Connection.js:226:16) at ExecutionContext._evaluateInternal (/Users/xxx/Downloads/auto-study-master/node_modules/puppeteer/lib/cjs/puppeteer/common/ExecutionContext.js:204:50) at ExecutionContext.evaluate (/Users/xxx/Downloads/auto-study-master/node_modules/puppeteer/lib/cjs/puppeteer/common/ExecutionContext.js:110:27) at DOMWorld.evaluate (/Users/xxx/Downloads/auto-study-master/node_modules/puppeteer/lib/cjs/puppeteer/common/DOMWorld.js:97:24) at runMicrotasks () at processTicksAndRejections (node:internal/process/task_queues:96:5) { originalMessage: 'Execution context was destroyed.' }
> 
> 视频播放，测试了好几次，差不多一个小时，就会挂掉，是网站做了限制吗

这个限制是我加的

**Comment by 1xiaocainiao** [comment]
> > > 可能是网站改版或者你的科目和我的不一样，导致页面元素也不一样。
> > 
> > 
> > Unhandled Rejection at: Promise Promise { ProtocolError: Protocol error (Runtime.callFunctionOn): Execution context was destroyed. at /Users/xxx/Downloads/auto-study-master/node_modules/puppeteer/lib/cjs/puppeteer/common/Connection.js:230:24 at new Promise () at CDPSession.send (/Users/xxx/Downloads/auto-study-master/node_modules/puppeteer/lib/cjs/puppeteer/common/Connection.js:226:16) at ExecutionContext._evaluateInternal (/Users/xxx/Downloads/auto-study-master/node_modules/puppeteer/lib/cjs/puppeteer/common/ExecutionContext.js:204:50) at ExecutionContext.evaluate (/Users/xxx/Downloads/auto-study-master/node_modules/puppeteer/lib/cjs/puppeteer/common/ExecutionContext.js:110:27) at DOMWorld.evaluate (/Users/xxx/Downloads/auto-study-master/node_modules/puppeteer/lib/cjs/puppeteer/common/DOMWorld.js:97:24) at runMicrotasks () at processTicksAndRejections (node:internal/process/task_queues:96:5) { originalMessage: 'Execution context was destroyed.' } } reason: ProtocolError: Protocol error (Runtime.callFunctionOn): Execution context was destroyed. at /Users/xxx/Downloads/auto-study-master/node_modules/puppeteer/lib/cjs/puppeteer/common/Connection.js:230:24 at new Promise () at CDPSession.send (/Users/xxx/Downloads/auto-study-master/node_modules/puppeteer/lib/cjs/puppeteer/common/Connection.js:226:16) at ExecutionContext._evaluateInternal (/Users/xxx/Downloads/auto-study-master/node_modules/puppeteer/lib/cjs/puppeteer/common/ExecutionContext.js:204:50) at ExecutionContext.evaluate (/Users/xxx/Downloads/auto-study-master/node_modules/puppeteer/lib/cjs/puppeteer/common/ExecutionContext.js:110:27) at DOMWorld.evaluate (/Users/xxx/Downloads/auto-study-master/node_modules/puppeteer/lib/cjs/puppeteer/common/DOMWorld.js:97:24) at runMicrotasks () at processTicksAndRejections (node:internal/process/task_queues:96:5) { originalMessage: 'Execution context was destroyed.' }
> > 视频播放，测试了好几次，差不多一个小时，就会挂掉，是网站做了限制吗
> 
> 这个限制是我加的

好的

**Comment by czyccc** [comment]
请问如何去掉此限制啊

**Comment by maxmeng93** [comment]
> 请问如何去掉此限制啊

可以自己研究下，反正没几行代码
