### ISSUE TITLE
课程第一个是作业怎么办

### ISSUE THREAD

**Issue by cbhhy** [maxmeng93/auto-study#15]
使用 data.json 缓存
study...
开始获取课程数据...
33169 - 毕业作业
Unhandled Rejection at: Promise Promise {
  <rejected> TypeError: page.waitForTimeout is not a function
      at getCourseDetail (E:\Git\auto-study\src\getCourseDetail.js:27:14)
      at processTicksAndRejections (node:internal/process/task_queues:96:5)
      at async getData (E:\Git\auto-study\src\getData.js:13:24)
      at async E:\Git\auto-study\src\index.js:59:3
} reason: TypeError: page.waitForTimeout is not a function
    at getCourseDetail (E:\Git\auto-study\src\getCourseDetail.js:27:14)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async getData (E:\Git\auto-study\src\getData.js:13:24)
    at async E:\Git\auto-study\src\index.js:59:3

报错信息如上，有什么办法解决嘛

**Comment by maxmeng93** [comment]
> 使用 data.json 缓存 study... 开始获取课程数据... 33169 - 毕业作业 Unhandled Rejection at: Promise Promise { TypeError: page.waitForTimeout is not a function at getCourseDetail (E:\Git\auto-study\src\getCourseDetail.js:27:14) at processTicksAndRejections (node:internal/process/task_queues:96:5) at async getData (E:\Git\auto-study\src\getData.js:13:24) at async E:\Git\auto-study\src\index.js:59:3 } reason: TypeError: page.waitForTimeout is not a function at getCourseDetail (E:\Git\auto-study\src\getCourseDetail.js:27:14) at processTicksAndRejections (node:internal/process/task_queues:96:5) at async getData (E:\Git\auto-study\src\getData.js:13:24) at async E:\Git\auto-study\src\index.js:59:3
> 
> 报错信息如上，有什么办法解决嘛

waitForTimeout 是 puppeteer 提供的方法，可能依赖版本下载的不对。对比下依赖版本，或者删掉依赖，重新用yarn安装

**Comment by cbhhy** [comment]
读不到缓存，每次开始学习都要重新看一遍
