### ISSUE TITLE
好像不能用了

### ISSUE THREAD

**Issue by SiMaLaoShi** [maxmeng93/auto-study#17]
ck没问题了，data.json一直是null

**Comment by SiMaLaoShi** [comment]
Unhandled Rejection at: Promise Promise {
  <rejected> ProtocolError: Protocol error (Runtime.callFunctionOn): Execution context was destroyed.
      at C:\Users\Bully\Desktop\git\auto-study\node_modules\puppeteer-core\lib\cjs\puppeteer\common\Connection.js:230:24
      at new Promise (<anonymous>)
      at CDPSession.send (C:\Users\Bully\Desktop\git\auto-study\node_modules\puppeteer-core\lib\cjs\puppeteer\common\Connection.js:226:16)
      at ExecutionContext._evaluateInternal (C:\Users\Bully\Desktop\git\auto-study\node_modules\puppeteer-core\lib\cjs\puppeteer\common\ExecutionContext.js:204:50)
      at ExecutionContext.evaluate (C:\Users\Bully\Desktop\git\auto-study\node_modules\puppeteer-core\lib\cjs\puppeteer\common\ExecutionContext.js:110:27)
      at DOMWorld.evaluate (C:\Users\Bully\Desktop\git\auto-study\node_modules\puppeteer-core\lib\cjs\puppeteer\common\DOMWorld.js:97:24)
      at processTicksAndRejections (node:internal/process/task_queues:96:5) {
    originalMessage: 'Execution context was destroyed.'
  }
} reason: ProtocolError: Protocol error (Runtime.callFunctionOn): Execution context was destroyed.
    at C:\Users\Bully\Desktop\git\auto-study\node_modules\puppeteer-core\lib\cjs\puppeteer\common\Connection.js:230:24
    at new Promise (<anonymous>)
    at CDPSession.send (C:\Users\Bully\Desktop\git\auto-study\node_modules\puppeteer-core\lib\cjs\puppeteer\common\Connection.js:226:16)
    at ExecutionContext._evaluateInternal (C:\Users\Bully\Desktop\git\auto-study\node_modules\puppeteer-core\lib\cjs\puppeteer\common\ExecutionContext.js:204:50)
    at ExecutionContext.evaluate (C:\Users\Bully\Desktop\git\auto-study\node_modules\puppeteer-core\lib\cjs\puppeteer\common\ExecutionContext.js:110:27)
    at DOMWorld.evaluate (C:\Users\Bully\Desktop\git\auto-study\node_modules\puppeteer-core\lib\cjs\puppeteer\common\DOMWorld.js:97:24)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  originalMessage: 'Execution context was destroyed.'
}
