### ISSUE TITLE
求看看啥情况

### ISSUE THREAD

**Issue by daijuyan** [maxmeng93/auto-study#2]
C:\Users\Administrator\Desktop\auto-study-master>yarn start
yarn run v1.22.19
warning package.json: No license field
warning ..\..\package.json: No license field
$ node ./src/index.js
13710 - 办公室管理
13698 - 法学概论
13740 - 个人与团队管理
13791 - 监督学
13928 - 行政组织学
Unhandled Rejection at: Promise Promise {
  <rejected> Error: Error: failed to find element matching selector ".activity-title > a.title"
      at ElementHandle.$eval (C:\Users\Administrator\Desktop\auto-study-master\node_modules\puppeteer\lib\cjs\puppeteer\common\JSHandle.js:880:19)
      at runMicrotasks (<anonymous>)
      at processTicksAndRejections (node:internal/process/task_queues:96:5)
      at async getCourseDetail (C:\Users\Administrator\Desktop\auto-study-master\src\getCourseDetail.js:35:19)
      at async getData (C:\Users\Administrator\Desktop\auto-study-master\src\getData.js:11:24)
      at async C:\Users\Administrator\Desktop\auto-study-master\src\index.js:58:3
} reason: Error: Error: failed to find element matching selector ".activity-title > a.title"
    at ElementHandle.$eval (C:\Users\Administrator\Desktop\auto-study-master\node_modules\puppeteer\lib\cjs\puppeteer\common\JSHandle.js:880:19)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async getCourseDetail (C:\Users\Administrator\Desktop\auto-study-master\src\getCourseDetail.js:35:19)
    at async getData (C:\Users\Administrator\Desktop\auto-study-master\src\getData.js:11:24)
    at async C:\Users\Administrator\Desktop\auto-study-master\src\index.js:58:3

**Comment by maxmeng93** [comment]
> C:\Users\Administrator\Desktop\auto-study-master>yarn start
> yarn run v1.22.19
> warning package.json: No license field
> warning ....\package.json: No license field
> $ node ./src/index.js
> 13710 - 办公室管理
> 13698 - 法学概论
> 13740 - 个人与团队管理
> 13791 - 监督学
> 13928 - 行政组织学
> Unhandled Rejection at: Promise Promise {
> Error: Error: failed to find element matching selector ".activity-title > a.title"
> at ElementHandle.$eval (C:\Users\Administrator\Desktop\auto-study-master\node_modules\puppeteer\lib\cjs\puppeteer\common\JSHandle.js:880:19)
> at runMicrotasks ()
> at processTicksAndRejections (node:internal/process/task_queues:96:5)
> at async getCourseDetail (C:\Users\Administrator\Desktop\auto-study-master\src\getCourseDetail.js:35:19)
> at async getData (C:\Users\Administrator\Desktop\auto-study-master\src\getData.js:11:24)
> at async C:\Users\Administrator\Desktop\auto-study-master\src\index.js:58:3
> } reason: Error: Error: failed to find element matching selector ".activity-title > a.title"
> at ElementHandle.$eval (C:\Users\Administrator\Desktop\auto-study-master\node_modules\puppeteer\lib\cjs\puppeteer\common\JSHandle.js:880:19)
> at runMicrotasks ()
> at processTicksAndRejections (node:internal/process/task_queues:96:5)
> at async getCourseDetail (C:\Users\Administrator\Desktop\auto-study-master\src\getCourseDetail.js:35:19)
> at async getData (C:\Users\Administrator\Desktop\auto-study-master\src\getData.js:11:24)
> at async C:\Users\Administrator\Desktop\auto-study-master\src\index.js:58:3

我这里没有问题。这个报错看log是没找到对应的DOM。你看下最后一个课程的页面是否和其他课程一样。如果一样就多试几次，如果不一样，那就是代码没有支持，自己改吧

**Comment by ichenc** [comment]
咋用啊，看不懂咋用啊

**Comment by maxmeng93** [comment]
> 咋用啊，看不懂咋用啊

看你也是做前端的，我这代码应该很简单吧

**Comment by ichenc** [comment]
这个刷完要用多长时间啊

**Comment by maxmeng93** [comment]
> 这个刷完要用多长时间啊

那得看你课程有多少
