### ISSUE TITLE
yarn start报错,又是puppeteer的坑

### ISSUE THREAD

**Issue by hzexe** [maxmeng93/auto-study#7]
试过两个windows版本,两个linux,都报相同的错误,希望规避有bug的版本
hzexe@e540:~/auto-study$ yarn start
yarn run v1.22.18
warning package.json: No license field
$ node ./src/index.js
Unhandled Rejection at: Promise Promise {
  <rejected> Error: Failed to launch the browser process! spawn /Applications/Google Chrome.app/Contents/MacOS/Google Chrome ENOENT

  TROUBLESHOOTING: https://github.com/puppeteer/puppeteer/blob/main/docs/troubleshooting.md

      at onClose (/home/hzexe/auto-study/node_modules/puppeteer/lib/cjs/puppeteer/node/BrowserRunner.js:241:20)
      at ChildProcess.<anonymous> (/home/hzexe/auto-study/node_modules/puppeteer/lib/cjs/puppeteer/node/BrowserRunner.js:233:85)
      at ChildProcess.emit (node:events:527:28)
      at Process.ChildProcess._handle.onexit (node:internal/child_process:289:12)
      at onErrorNT (node:internal/child_process:478:16)
      at processTicksAndRejections (node:internal/process/task_queues:83:21)
} reason: Error: Failed to launch the browser process! spawn /Applications/Google Chrome.app/Contents/MacOS/Google Chrome ENOENT

**Comment by maxmeng93** [comment]
Chrome浏览器路径不对
